# Generated by Django 5.2.7 on 2025-10-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["created_date"]},
        ),
    ]
